eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka

discovery.server.ui-uri=http://discovery-server:8761
discovery.server.base-uri=http://discovery-server:8761

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:8181/auth/realms/spring-boot-microservices-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://keycloak:8080/auth/realms/spring-boot-microservices-realm/protocol/openid-connect/certs}
management.zipkin.tracing.endpoint=http://tempo:9411/api/v2/spans
