spring.data.mongodb.uri=mongodb://root:password@mongodb:27017/product_db?authSource=admin

eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka

management.zipkin.tracing.endpoint=http://tempo:9411/api/v2/spans
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/auth/realms/spring-boot-microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/spring-boot-microservices-realm/protocol/openid-connect/certs
